version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/test

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root  # Execute the script as root
    
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root  # Execute the script as root
    
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root  # Execute the script as root
